# Generated by Django 5.1 on 2024-09-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'verbose_name': 'Дом', 'verbose_name_plural': 'Доступные дома'},
        ),
        migrations.AddField(
            model_name='apartment',
            name='number',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='address',
            field=models.CharField(max_length=255, unique=True, verbose_name='Адрес'),
        ),
    ]
