# Generated by Django 5.1 on 2024-09-07 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_house_options_apartment_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'verbose_name': 'Квартира', 'verbose_name_plural': 'Доступные квартиры'},
        ),
        migrations.AlterModelOptions(
            name='watermeter',
            options={'verbose_name': 'Счётчик', 'verbose_name_plural': 'Счётчики'},
        ),
    ]
