# Generated by Django 5.1 on 2024-09-07 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_apartment_options_alter_watermeter_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип счётчика')),
                ('unit', models.CharField(max_length=50, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Тип счётчика',
                'verbose_name_plural': 'Типы счётчиков',
            },
        ),
        migrations.AddField(
            model_name='watermeter',
            name='meter_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер счётчика'),
        ),
        migrations.AddField(
            model_name='watermeter',
            name='meter_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meters', to='home.metertype', verbose_name='Тип счётчика'),
        ),
    ]
