# Generated by Django 5.1 on 2024-09-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_metertype_watermeter_meter_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watermeter',
            name='readings',
            field=models.JSONField(blank=True, null=True, verbose_name='Показания'),
        ),
    ]
