# Generated by Django 5.1 on 2024-09-07 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20240907_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watermeter',
            name='meter_number',
            field=models.CharField(default='Unknown', max_length=50, verbose_name='Номер счётчика'),
        ),
        migrations.AlterField(
            model_name='watermeter',
            name='meter_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='meters', to='home.metertype', verbose_name='Тип счётчика'),
        ),
    ]
