# Generated by Django 5.1 on 2024-09-07 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_watermeter_meter_number_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WaterMeter',
            new_name='Meter',
        ),
    ]
