# Generated by Django 5.1 on 2024-09-07 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_water_charge_utilitybill_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='name',
        ),
        migrations.AddField(
            model_name='tariff',
            name='custom_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название тарифа'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='meter_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tariffs', to='home.metertype', verbose_name='Тип счётчика'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу'),
        ),
    ]
