# Generated by Django 5.1 on 2024-09-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_tariff_name_tariff_custom_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='unit',
            field=models.CharField(blank=True, max_length=50, verbose_name='Единица измерения'),
        ),
    ]
