# Generated by Django 5.1 on 2024-09-08 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_tariff_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tariff',
            options={'verbose_name': 'Тариф', 'verbose_name_plural': 'Тарифы'},
        ),
    ]
