# Generated by Django 5.1 on 2024-09-08 08:28

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_tariff_options'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE home_utilitybill ALTER COLUMN charge TYPE text USING charge::text;",
            reverse_sql="ALTER TABLE home_utilitybill ALTER COLUMN charge TYPE numeric USING charge::numeric;"
        ),
        migrations.RunSQL(
            "ALTER TABLE home_utilitybill ALTER COLUMN charge TYPE jsonb USING charge::jsonb;",
            reverse_sql="ALTER TABLE home_utilitybill ALTER COLUMN charge TYPE text USING charge::text;"
        ),
    ]