# Generated by Django 5.1 on 2024-09-08 16:34

import home.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_calculationprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[home.validators.validate_area]),
        ),
    ]
