# Generated by Django 5.1 on 2024-09-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_apartment_area_alter_apartment_house_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='meter_number',
            field=models.CharField(max_length=50, verbose_name='Номер счётчика'),
        ),
    ]
