# Generated by Django 5.1 on 2024-09-08 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_meter_meter_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='custom_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Название тарифа'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='meter_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tariffs', to='home.metertype', unique=True, verbose_name='Тип счётчика'),
        ),
    ]
