# Generated by Django 5.1 on 2024-09-08 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_tariff_custom_name_alter_tariff_meter_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='meter_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tariffs', to='home.metertype', verbose_name='Тип счётчика'),
        ),
        migrations.AddConstraint(
            model_name='tariff',
            constraint=models.UniqueConstraint(fields=('meter_type',), name='unique_meter_type_in_tariff'),
        ),
    ]
